# Generated by Django 3.0.5 on 2020-04-04 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_timezone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_starttime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ap_endtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ap_u_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='djangofullthrottleapp.Users')),
            ],
        ),
    ]
